version: "3.8"

services:
  eureka-serviceregistry:
    image: eureka-serviceregistry
    container_name: eureka-serviceregistry
    build: ./eureka
    tty: true
    networks:
      - demo
    ports:
      - "8761:8761"
  
  
  frontend:
    build: ./frontend
    container_name: frontend
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - demo
  
  media-microservice:
    image: media-microservice
    container_name: media-microservice
    build:
      context: ./media-microservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8085:8085"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: bazabaza
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: mediaMicroservice?createDatabaseIfNotExist=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    depends_on:
      - eureka-serviceregistry
      - mysql
   
  profile-microservice:
    image: profile-microservice
    container_name: profile-microservice
    build:
      context: ./profileMicroservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8087:8087"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: bazabaza
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: profileMicroservice?createDatabaseIfNotExist=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    depends_on:
      - eureka-serviceregistry
      - mysql
      
  search-microservice:
    image: search-microservice
    container_name: search-microservice
    build:
      context: ./search-microservice
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - demo
    ports:
      - "8088:8088"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: bazabaza
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: searchMicroservice?createDatabaseIfNotExist=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    depends_on:
      - eureka-serviceregistry
      - mysql
      
    
  zuul:
    image: zuul
    container_name: zuul
    build: ./zuul
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-serviceregistry:8761/eureka/
    tty: true
    networks:
      - demo
    ports:
      - "8083:8083"
    depends_on:
      - eureka-serviceregistry
      - profile-microservice
      - media-microservice
      - search-microservice
      
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    networks:
      - demo
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: bazabaza
      MYSQL_USER: root
      MYSQL_PASSWORD: bazabaza
  
      
networks:
  demo:
    name: demo
    driver: bridge