version: "3.8"
services:

  media-microservice:
    build: ./media-microservice
    image: media-microservice
    container_name: media-microservice
    ports:
      - "8087:8087"
    tty: true
    networks:
      - demo
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: postgres
      DATABASE_HOST: postgres
      DATABASE_SCHEMA: mediaMicroservices
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    networks:
      - demo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/
    environment: 
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=mediaMicroservices
      

      
networks:
  demo:
    name: demo
    driver: bridge