version: "3.8"
services:

  media-microservice:
    image: media-microservice
    container_name: media-microservice
    build:
      context: ./media-microservice
      dockerfile: Dockerfile
    tty: true
    networks:
      - demo
    ports:
      - "8085:8085"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: bazabaza
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: nistagram
    depends_on:
      - mysql
      
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    networks:
      - demo
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: bazabaza
      MYSQL_USER: root
      MYSQL_PASSWORD: bazabaza
  
      
networks:
  demo:
    name: demo
    driver: bridge
